### ISSUE TITLE
Add support for multiline titles or underline

### ISSUE THREAD

**Issue by PibePlayer** [thecodrr/boxx#4]
I'm currently trying to have a title underlined, and this is the result I got:
Code:
![Code](https://user-images.githubusercontent.com/3812153/73115859-57e46f00-3f0b-11ea-956d-5e3ad73a7805.jpg)

Result:
![Result](https://user-images.githubusercontent.com/3812153/73115864-63d03100-3f0b-11ea-9ecd-c1140da1f537.jpg)

**Comment by thecodrr** [comment]
Will fix ASAP.
