### ISSUE TITLE
Issues with colorized strings from Crayon

### ISSUE THREAD

**Issue by PibePlayer** [thecodrr/boxx#5]
I'm trying to use colorized strings to use different colors inside a box, and those are the results I got:
Code:
![Code](https://user-images.githubusercontent.com/3812153/73116218-5453e680-3f11-11ea-9c6f-01bb0b221125.jpg)

Original (Without Colors):
![Original](https://user-images.githubusercontent.com/3812153/73116223-659cf300-3f11-11ea-8374-ff9212f6fe7c.jpg)

Result (With crayon colorized string):
![Result](https://user-images.githubusercontent.com/3812153/73116227-79e0f000-3f11-11ea-8e1a-6cb7b7d658ef.jpg)

**Comment by thecodrr** [comment]
Taking a look right now.

**Comment by thecodrr** [comment]
Fixed.
